services:
  mariadb:
    build: containers/mariadb/.
    container_name: mariadb
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: on-failure

  nginx:
    build: containers/nginx
    container_name: nginx
    env_file: .env
    environment:
      NGINX_HOST: ${NGINX_HOST}
      NGINX_PORT: ${NGINX_PORT}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - "80:80"
    volumes:
      - nginx_data:/var/www/html
    restart: on-failure

  wordpress:
    build: containers/wordpress/.
    container_name: wordpress
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - "80"
    volumes:
      - wordpress_data:/var/www/html
    restart: on-failure

volumes:
  mariadb_data:
  nginx_data:
  wordpress_data: